export const meetingList = [
  {
    id: 1,
    title: "스터디 모임",
    participant: 2,
    total: 4,
    subTitle: "코딩 테스트 자바 스터디",
    address: "경기 용인시 기흥구 강남서로 9",
    deadline: "2022-12-29 12:00",
    status: false,
    like: false,
  },
  {
    id: 2,
    title: "제목",
    participant: 0,
    total: 0,
    subTitle: "소제목",
    address: "경기 용인시 기흥구 강남서로 9",
    deadline: "2022-12-29 12:00",
    status: true,
    like: false,
  },
  {
    id: 3,
    title: "제목",
    participant: 0,
    total: 0,
    subTitle: "소제목",
    address: "경기 용인시 기흥구 강남서로 9",
    deadline: "2022-12-29 12:00",
    status: true,
    like: false,
  },
  {
    id: 4,
    title: "제목",
    participant: 0,
    total: 0,
    subTitle: "소제목",
    address: "경기 용인시 기흥구 강남서로 9",
    deadline: "2022-12-29 12:00",
    status: true,
    like: false,
  },
];
